# Generated by Django 3.2.11 on 2022-01-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="HubUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("middle_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("user", "User"),
                            ("viewer", "Viewer"),
                            ("other", "Other"),
                        ],
                        default="user",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(help_text="Slug", max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_password_changed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
